/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApexRouteImport } from './routes/apex'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApexRoute = ApexRouteImport.update({
  id: '/apex',
  path: '/apex',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apex': typeof ApexRoute
  '/docs': typeof DocsRoute
  '/gallery': typeof GalleryRoute
  '/playground': typeof PlaygroundRoute
  '/prompts': typeof PromptsRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRoute
  '/workflows': typeof WorkflowsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apex': typeof ApexRoute
  '/docs': typeof DocsRoute
  '/gallery': typeof GalleryRoute
  '/playground': typeof PlaygroundRoute
  '/prompts': typeof PromptsRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRoute
  '/workflows': typeof WorkflowsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apex': typeof ApexRoute
  '/docs': typeof DocsRoute
  '/gallery': typeof GalleryRoute
  '/playground': typeof PlaygroundRoute
  '/prompts': typeof PromptsRoute
  '/references': typeof ReferencesRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRoute
  '/workflows': typeof WorkflowsRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apex'
    | '/docs'
    | '/gallery'
    | '/playground'
    | '/prompts'
    | '/references'
    | '/settings'
    | '/videos'
    | '/workflows'
    | '/api/generate-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apex'
    | '/docs'
    | '/gallery'
    | '/playground'
    | '/prompts'
    | '/references'
    | '/settings'
    | '/videos'
    | '/workflows'
    | '/api/generate-image'
  id:
    | '__root__'
    | '/'
    | '/apex'
    | '/docs'
    | '/gallery'
    | '/playground'
    | '/prompts'
    | '/references'
    | '/settings'
    | '/videos'
    | '/workflows'
    | '/api/generate-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApexRoute: typeof ApexRoute
  DocsRoute: typeof DocsRoute
  GalleryRoute: typeof GalleryRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PromptsRoute: typeof PromptsRoute
  ReferencesRoute: typeof ReferencesRoute
  SettingsRoute: typeof SettingsRoute
  VideosRoute: typeof VideosRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apex': {
      id: '/apex'
      path: '/apex'
      fullPath: '/apex'
      preLoaderRoute: typeof ApexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApexRoute: ApexRoute,
  DocsRoute: DocsRoute,
  GalleryRoute: GalleryRoute,
  PlaygroundRoute: PlaygroundRoute,
  PromptsRoute: PromptsRoute,
  ReferencesRoute: ReferencesRoute,
  SettingsRoute: SettingsRoute,
  VideosRoute: VideosRoute,
  WorkflowsRoute: WorkflowsRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
