/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as ColorsShowRouteImport } from './routes/colors-show'
import { Route as ComfyRouteImport } from './routes/comfy'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentMachineRouteImport } from './routes/content-machine'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditRouteImport } from './routes/edit'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as HeygenTemplatesRouteImport } from './routes/heygen-templates'
import { Route as HomeRouteImport } from './routes/home'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as LipsyncRouteImport } from './routes/lipsync'
import { Route as LiveStudioRouteImport } from './routes/live-studio'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MotionRouteImport } from './routes/motion'
import { Route as MusicVideoRouteImport } from './routes/music-video'
import { Route as NexusarbRouteImport } from './routes/nexusarb'
import { Route as OrchestrateRouteImport } from './routes/orchestrate'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PhotoEditRouteImport } from './routes/photo-edit'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReshootRouteImport } from './routes/reshoot'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SceneBuilderRouteImport } from './routes/scene-builder'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpeechRouteImport } from './routes/speech'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SplitRealityRouteImport } from './routes/split-reality'
import { Route as StoryboardRouteImport } from './routes/storyboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as UgcRouteImport } from './routes/ugc'
import { Route as UgcLineRouteImport } from './routes/ugc-line'
import { Route as VideoEditorRouteImport } from './routes/video-editor'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as AdminComfyRouteImport } from './routes/admin.comfy'
import { Route as AdminCostsRouteImport } from './routes/admin.costs'
import { Route as AdminOrchestrationRouteImport } from './routes/admin.orchestration'
import { Route as AdminSiteImagesRouteImport } from './routes/admin.site-images'
import { Route as AdminSmokeRouteImport } from './routes/admin.smoke'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminWorkflowsRouteImport } from './routes/admin.workflows'
import { Route as ApiEstimateRouteImport } from './routes/api/estimate'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as CliIndexRouteImport } from './routes/cli.index'
import { Route as CliAuthorizeRouteImport } from './routes/cli.authorize'
import { Route as CreatorDashboardRouteImport } from './routes/creator.dashboard'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ApiAdminRunSmokeStep14RouteImport } from './routes/api/admin/run-smoke-step14'
import { Route as ApiAdminUploadSiteImageRouteImport } from './routes/api/admin/upload-site-image'
import { Route as ApiPublicCheckApiBalancesRouteImport } from './routes/api/public/check-api-balances'
import { Route as ApiPublicFreeMonthlyGrantRouteImport } from './routes/api/public/free-monthly-grant'
import { Route as ApiPublicGenerateRouteImport } from './routes/api/public/generate'
import { Route as ApiPublicLifecycleEmailsRouteImport } from './routes/api/public/lifecycle-emails'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiPublicSiteImagesRouteImport } from './routes/api/public/site-images'
import { Route as ApiPublicWatermarkImageRouteImport } from './routes/api/public/watermark-image'
import { Route as ApiPublicWatermarkVideoRouteImport } from './routes/api/public/watermark-video'
import { Route as ApiUgcLineImagesRouteImport } from './routes/api/ugc-line/images'
import { Route as ApiUgcLineScriptsRouteImport } from './routes/api/ugc-line/scripts'
import { Route as ApiUgcLineVariationsRouteImport } from './routes/api/ugc-line/variations'
import { Route as ApiVideoAgentEnhanceRouteImport } from './routes/api/video-agent/enhance'
import { Route as ApiVideoAgentFinalizeRouteImport } from './routes/api/video-agent/finalize'
import { Route as ApiVideoAgentGenerateRouteImport } from './routes/api/video-agent/generate'
import { Route as ApiVideoAgentMessagesRouteImport } from './routes/api/video-agent/messages'
import { Route as ApiVideoAgentSubmitRouteImport } from './routes/api/video-agent/submit'
import { Route as ApiPublicJobsTickRouteImport } from './routes/api/public/jobs/tick'
import { Route as ApiPublicPaymentsSweepStuckRouteImport } from './routes/api/public/payments/sweep-stuck'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok/callback'
import { Route as ApiPublicWorkersHealthRouteImport } from './routes/api/public/workers/health'
import { Route as ApiPublicWorkersRegisterRouteImport } from './routes/api/public/workers/register'
import { Route as ApiVideoAgentStatusVideoIdRouteImport } from './routes/api/video-agent/status.$videoId'
import { Route as ApiPublicCliDevicePollRouteImport } from './routes/api/public/cli/device/poll'
import { Route as ApiPublicCliDeviceStartRouteImport } from './routes/api/public/cli/device/start'
import { Route as ApiPublicWorkersFilesNameRouteImport } from './routes/api/public/workers/files/$name'

const BeatReelLazyRouteImport = createFileRoute('/beat-reel')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agent.lazy').then((d) => d.Route))
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/avatar.lazy').then((d) => d.Route))
const BeatReelLazyRoute = BeatReelLazyRouteImport.update({
  id: '/beat-reel',
  path: '/beat-reel',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/beat-reel.lazy').then((d) => d.Route))
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/billing.lazy').then((d) => d.Route))
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/canvas.lazy').then((d) => d.Route))
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/clips.lazy').then((d) => d.Route))
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/colors.lazy').then((d) => d.Route))
const ColorsShowRoute = ColorsShowRouteImport.update({
  id: '/colors-show',
  path: '/colors-show',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/colors-show.lazy').then((d) => d.Route))
const ComfyRoute = ComfyRouteImport.update({
  id: '/comfy',
  path: '/comfy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/comfy.lazy').then((d) => d.Route))
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/connect.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const ContentMachineRoute = ContentMachineRouteImport.update({
  id: '/content-machine',
  path: '/content-machine',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/content-machine.lazy').then((d) => d.Route),
)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/edit.lazy').then((d) => d.Route))
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/editor.lazy').then((d) => d.Route))
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/gallery.lazy').then((d) => d.Route))
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/gifts.lazy').then((d) => d.Route))
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/growth.lazy').then((d) => d.Route))
const HeygenTemplatesRoute = HeygenTemplatesRouteImport.update({
  id: '/heygen-templates',
  path: '/heygen-templates',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/heygen-templates.lazy').then((d) => d.Route),
)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/kids.lazy').then((d) => d.Route))
const LipsyncRoute = LipsyncRouteImport.update({
  id: '/lipsync',
  path: '/lipsync',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/lipsync.lazy').then((d) => d.Route))
const LiveStudioRoute = LiveStudioRouteImport.update({
  id: '/live-studio',
  path: '/live-studio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/live-studio.lazy').then((d) => d.Route))
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/marketplace.lazy').then((d) => d.Route))
const MotionRoute = MotionRouteImport.update({
  id: '/motion',
  path: '/motion',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/motion.lazy').then((d) => d.Route))
const MusicVideoRoute = MusicVideoRouteImport.update({
  id: '/music-video',
  path: '/music-video',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/music-video.lazy').then((d) => d.Route))
const NexusarbRoute = NexusarbRouteImport.update({
  id: '/nexusarb',
  path: '/nexusarb',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/nexusarb.lazy').then((d) => d.Route))
const OrchestrateRoute = OrchestrateRouteImport.update({
  id: '/orchestrate',
  path: '/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/partners.lazy').then((d) => d.Route))
const PhotoEditRoute = PhotoEditRouteImport.update({
  id: '/photo-edit',
  path: '/photo-edit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/photo-edit.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const ReshootRoute = ReshootRouteImport.update({
  id: '/reshoot',
  path: '/reshoot',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reshoot.lazy').then((d) => d.Route))
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/roadmap.lazy').then((d) => d.Route))
const SceneBuilderRoute = SceneBuilderRouteImport.update({
  id: '/scene-builder',
  path: '/scene-builder',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scene-builder.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechRoute = SpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/speech.lazy').then((d) => d.Route))
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/spin.lazy').then((d) => d.Route))
const SplitRealityRoute = SplitRealityRouteImport.update({
  id: '/split-reality',
  path: '/split-reality',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/split-reality.lazy').then((d) => d.Route))
const StoryboardRoute = StoryboardRouteImport.update({
  id: '/storyboard',
  path: '/storyboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/storyboard.lazy').then((d) => d.Route))
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/studio.lazy').then((d) => d.Route))
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/templates.lazy').then((d) => d.Route))
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tiktok.lazy').then((d) => d.Route))
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/tutorial.lazy').then((d) => d.Route))
const UgcRoute = UgcRouteImport.update({
  id: '/ugc',
  path: '/ugc',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ugc.lazy').then((d) => d.Route))
const UgcLineRoute = UgcLineRouteImport.update({
  id: '/ugc-line',
  path: '/ugc-line',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ugc-line.lazy').then((d) => d.Route))
const VideoEditorRoute = VideoEditorRouteImport.update({
  id: '/video-editor',
  path: '/video-editor',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/video-editor.lazy').then((d) => d.Route))
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/workflows.lazy').then((d) => d.Route))
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.assets.lazy').then((d) => d.Route))
const AdminComfyRoute = AdminComfyRouteImport.update({
  id: '/comfy',
  path: '/comfy',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.comfy.lazy').then((d) => d.Route))
const AdminCostsRoute = AdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.costs.lazy').then((d) => d.Route))
const AdminOrchestrationRoute = AdminOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.orchestration.lazy').then((d) => d.Route),
)
const AdminSiteImagesRoute = AdminSiteImagesRouteImport.update({
  id: '/site-images',
  path: '/site-images',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.site-images.lazy').then((d) => d.Route),
)
const AdminSmokeRoute = AdminSmokeRouteImport.update({
  id: '/smoke',
  path: '/smoke',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.smoke.lazy').then((d) => d.Route))
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.templates.lazy').then((d) => d.Route),
)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.workflows.lazy').then((d) => d.Route),
)
const ApiEstimateRoute = ApiEstimateRouteImport.update({
  id: '/api/estimate',
  path: '/api/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CliIndexRoute = CliIndexRouteImport.update({
  id: '/cli/',
  path: '/cli/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cli.index.lazy').then((d) => d.Route))
const CliAuthorizeRoute = CliAuthorizeRouteImport.update({
  id: '/cli/authorize',
  path: '/cli/authorize',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cli.authorize.lazy').then((d) => d.Route))
const CreatorDashboardRoute = CreatorDashboardRouteImport.update({
  id: '/creator/dashboard',
  path: '/creator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/creator.dashboard.lazy').then((d) => d.Route),
)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/guides.index.lazy').then((d) => d.Route))
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/guides.$slug.lazy').then((d) => d.Route))
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/legal.$slug.lazy').then((d) => d.Route))
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/r.$token.lazy').then((d) => d.Route))
const ApiAdminRunSmokeStep14Route = ApiAdminRunSmokeStep14RouteImport.update({
  id: '/api/admin/run-smoke-step14',
  path: '/api/admin/run-smoke-step14',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadSiteImageRoute = ApiAdminUploadSiteImageRouteImport.update({
  id: '/api/admin/upload-site-image',
  path: '/api/admin/upload-site-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckApiBalancesRoute =
  ApiPublicCheckApiBalancesRouteImport.update({
    id: '/api/public/check-api-balances',
    path: '/api/public/check-api-balances',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFreeMonthlyGrantRoute =
  ApiPublicFreeMonthlyGrantRouteImport.update({
    id: '/api/public/free-monthly-grant',
    path: '/api/public/free-monthly-grant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGenerateRoute = ApiPublicGenerateRouteImport.update({
  id: '/api/public/generate',
  path: '/api/public/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLifecycleEmailsRoute =
  ApiPublicLifecycleEmailsRouteImport.update({
    id: '/api/public/lifecycle-emails',
    path: '/api/public/lifecycle-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSiteImagesRoute = ApiPublicSiteImagesRouteImport.update({
  id: '/api/public/site-images',
  path: '/api/public/site-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWatermarkImageRoute = ApiPublicWatermarkImageRouteImport.update({
  id: '/api/public/watermark-image',
  path: '/api/public/watermark-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWatermarkVideoRoute = ApiPublicWatermarkVideoRouteImport.update({
  id: '/api/public/watermark-video',
  path: '/api/public/watermark-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUgcLineImagesRoute = ApiUgcLineImagesRouteImport.update({
  id: '/api/ugc-line/images',
  path: '/api/ugc-line/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUgcLineScriptsRoute = ApiUgcLineScriptsRouteImport.update({
  id: '/api/ugc-line/scripts',
  path: '/api/ugc-line/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUgcLineVariationsRoute = ApiUgcLineVariationsRouteImport.update({
  id: '/api/ugc-line/variations',
  path: '/api/ugc-line/variations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentEnhanceRoute = ApiVideoAgentEnhanceRouteImport.update({
  id: '/api/video-agent/enhance',
  path: '/api/video-agent/enhance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentFinalizeRoute = ApiVideoAgentFinalizeRouteImport.update({
  id: '/api/video-agent/finalize',
  path: '/api/video-agent/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentGenerateRoute = ApiVideoAgentGenerateRouteImport.update({
  id: '/api/video-agent/generate',
  path: '/api/video-agent/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentMessagesRoute = ApiVideoAgentMessagesRouteImport.update({
  id: '/api/video-agent/messages',
  path: '/api/video-agent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoAgentSubmitRoute = ApiVideoAgentSubmitRouteImport.update({
  id: '/api/video-agent/submit',
  path: '/api/video-agent/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsTickRoute = ApiPublicJobsTickRouteImport.update({
  id: '/api/public/jobs/tick',
  path: '/api/public/jobs/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsSweepStuckRoute =
  ApiPublicPaymentsSweepStuckRouteImport.update({
    id: '/api/public/payments/sweep-stuck',
    path: '/api/public/payments/sweep-stuck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkersHealthRoute = ApiPublicWorkersHealthRouteImport.update({
  id: '/api/public/workers/health',
  path: '/api/public/workers/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkersRegisterRoute =
  ApiPublicWorkersRegisterRouteImport.update({
    id: '/api/public/workers/register',
    path: '/api/public/workers/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVideoAgentStatusVideoIdRoute =
  ApiVideoAgentStatusVideoIdRouteImport.update({
    id: '/api/video-agent/status/$videoId',
    path: '/api/video-agent/status/$videoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCliDevicePollRoute = ApiPublicCliDevicePollRouteImport.update({
  id: '/api/public/cli/device/poll',
  path: '/api/public/cli/device/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCliDeviceStartRoute = ApiPublicCliDeviceStartRouteImport.update({
  id: '/api/public/cli/device/start',
  path: '/api/public/cli/device/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkersFilesNameRoute =
  ApiPublicWorkersFilesNameRouteImport.update({
    id: '/api/public/workers/files/$name',
    path: '/api/public/workers/files/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/colors-show': typeof ColorsShowRoute
  '/comfy': typeof ComfyRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/content-machine': typeof ContentMachineRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/editor': typeof EditorRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/growth': typeof GrowthRoute
  '/heygen-templates': typeof HeygenTemplatesRoute
  '/home': typeof HomeRoute
  '/kids': typeof KidsRoute
  '/lipsync': typeof LipsyncRoute
  '/live-studio': typeof LiveStudioRoute
  '/marketplace': typeof MarketplaceRoute
  '/motion': typeof MotionRoute
  '/music-video': typeof MusicVideoRoute
  '/nexusarb': typeof NexusarbRoute
  '/orchestrate': typeof OrchestrateRoute
  '/partners': typeof PartnersRoute
  '/photo-edit': typeof PhotoEditRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reshoot': typeof ReshootRoute
  '/roadmap': typeof RoadmapRoute
  '/scene-builder': typeof SceneBuilderRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speech': typeof SpeechRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/tutorial': typeof TutorialRoute
  '/ugc': typeof UgcRoute
  '/ugc-line': typeof UgcLineRoute
  '/video-editor': typeof VideoEditorRoute
  '/workflows': typeof WorkflowsRoute
  '/beat-reel': typeof BeatReelLazyRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/comfy': typeof AdminComfyRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/site-images': typeof AdminSiteImagesRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/api/estimate': typeof ApiEstimateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/cli/': typeof CliIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/admin/run-smoke-step14': typeof ApiAdminRunSmokeStep14Route
  '/api/admin/upload-site-image': typeof ApiAdminUploadSiteImageRoute
  '/api/public/check-api-balances': typeof ApiPublicCheckApiBalancesRoute
  '/api/public/free-monthly-grant': typeof ApiPublicFreeMonthlyGrantRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/lifecycle-emails': typeof ApiPublicLifecycleEmailsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/site-images': typeof ApiPublicSiteImagesRoute
  '/api/public/watermark-image': typeof ApiPublicWatermarkImageRoute
  '/api/public/watermark-video': typeof ApiPublicWatermarkVideoRoute
  '/api/ugc-line/images': typeof ApiUgcLineImagesRoute
  '/api/ugc-line/scripts': typeof ApiUgcLineScriptsRoute
  '/api/ugc-line/variations': typeof ApiUgcLineVariationsRoute
  '/api/video-agent/enhance': typeof ApiVideoAgentEnhanceRoute
  '/api/video-agent/finalize': typeof ApiVideoAgentFinalizeRoute
  '/api/video-agent/generate': typeof ApiVideoAgentGenerateRoute
  '/api/video-agent/messages': typeof ApiVideoAgentMessagesRoute
  '/api/video-agent/submit': typeof ApiVideoAgentSubmitRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/payments/sweep-stuck': typeof ApiPublicPaymentsSweepStuckRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/workers/health': typeof ApiPublicWorkersHealthRoute
  '/api/public/workers/register': typeof ApiPublicWorkersRegisterRoute
  '/api/video-agent/status/$videoId': typeof ApiVideoAgentStatusVideoIdRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
  '/api/public/workers/files/$name': typeof ApiPublicWorkersFilesNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/colors-show': typeof ColorsShowRoute
  '/comfy': typeof ComfyRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/content-machine': typeof ContentMachineRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/editor': typeof EditorRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/growth': typeof GrowthRoute
  '/heygen-templates': typeof HeygenTemplatesRoute
  '/home': typeof HomeRoute
  '/kids': typeof KidsRoute
  '/lipsync': typeof LipsyncRoute
  '/live-studio': typeof LiveStudioRoute
  '/marketplace': typeof MarketplaceRoute
  '/motion': typeof MotionRoute
  '/music-video': typeof MusicVideoRoute
  '/nexusarb': typeof NexusarbRoute
  '/orchestrate': typeof OrchestrateRoute
  '/partners': typeof PartnersRoute
  '/photo-edit': typeof PhotoEditRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reshoot': typeof ReshootRoute
  '/roadmap': typeof RoadmapRoute
  '/scene-builder': typeof SceneBuilderRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speech': typeof SpeechRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/tutorial': typeof TutorialRoute
  '/ugc': typeof UgcRoute
  '/ugc-line': typeof UgcLineRoute
  '/video-editor': typeof VideoEditorRoute
  '/workflows': typeof WorkflowsRoute
  '/beat-reel': typeof BeatReelLazyRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/comfy': typeof AdminComfyRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/site-images': typeof AdminSiteImagesRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/api/estimate': typeof ApiEstimateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/cli': typeof CliIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/api/admin/run-smoke-step14': typeof ApiAdminRunSmokeStep14Route
  '/api/admin/upload-site-image': typeof ApiAdminUploadSiteImageRoute
  '/api/public/check-api-balances': typeof ApiPublicCheckApiBalancesRoute
  '/api/public/free-monthly-grant': typeof ApiPublicFreeMonthlyGrantRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/lifecycle-emails': typeof ApiPublicLifecycleEmailsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/site-images': typeof ApiPublicSiteImagesRoute
  '/api/public/watermark-image': typeof ApiPublicWatermarkImageRoute
  '/api/public/watermark-video': typeof ApiPublicWatermarkVideoRoute
  '/api/ugc-line/images': typeof ApiUgcLineImagesRoute
  '/api/ugc-line/scripts': typeof ApiUgcLineScriptsRoute
  '/api/ugc-line/variations': typeof ApiUgcLineVariationsRoute
  '/api/video-agent/enhance': typeof ApiVideoAgentEnhanceRoute
  '/api/video-agent/finalize': typeof ApiVideoAgentFinalizeRoute
  '/api/video-agent/generate': typeof ApiVideoAgentGenerateRoute
  '/api/video-agent/messages': typeof ApiVideoAgentMessagesRoute
  '/api/video-agent/submit': typeof ApiVideoAgentSubmitRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/payments/sweep-stuck': typeof ApiPublicPaymentsSweepStuckRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/workers/health': typeof ApiPublicWorkersHealthRoute
  '/api/public/workers/register': typeof ApiPublicWorkersRegisterRoute
  '/api/video-agent/status/$videoId': typeof ApiVideoAgentStatusVideoIdRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
  '/api/public/workers/files/$name': typeof ApiPublicWorkersFilesNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/avatar': typeof AvatarRoute
  '/billing': typeof BillingRoute
  '/canvas': typeof CanvasRoute
  '/clips': typeof ClipsRoute
  '/colors': typeof ColorsRoute
  '/colors-show': typeof ColorsShowRoute
  '/comfy': typeof ComfyRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/content-machine': typeof ContentMachineRoute
  '/dashboard': typeof DashboardRoute
  '/edit': typeof EditRoute
  '/editor': typeof EditorRoute
  '/gallery': typeof GalleryRoute
  '/gifts': typeof GiftsRoute
  '/growth': typeof GrowthRoute
  '/heygen-templates': typeof HeygenTemplatesRoute
  '/home': typeof HomeRoute
  '/kids': typeof KidsRoute
  '/lipsync': typeof LipsyncRoute
  '/live-studio': typeof LiveStudioRoute
  '/marketplace': typeof MarketplaceRoute
  '/motion': typeof MotionRoute
  '/music-video': typeof MusicVideoRoute
  '/nexusarb': typeof NexusarbRoute
  '/orchestrate': typeof OrchestrateRoute
  '/partners': typeof PartnersRoute
  '/photo-edit': typeof PhotoEditRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reshoot': typeof ReshootRoute
  '/roadmap': typeof RoadmapRoute
  '/scene-builder': typeof SceneBuilderRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speech': typeof SpeechRoute
  '/spin': typeof SpinRoute
  '/split-reality': typeof SplitRealityRoute
  '/storyboard': typeof StoryboardRoute
  '/studio': typeof StudioRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/tiktok': typeof TiktokRoute
  '/tutorial': typeof TutorialRoute
  '/ugc': typeof UgcRoute
  '/ugc-line': typeof UgcLineRoute
  '/video-editor': typeof VideoEditorRoute
  '/workflows': typeof WorkflowsRoute
  '/beat-reel': typeof BeatReelLazyRoute
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/comfy': typeof AdminComfyRoute
  '/admin/costs': typeof AdminCostsRoute
  '/admin/orchestration': typeof AdminOrchestrationRoute
  '/admin/site-images': typeof AdminSiteImagesRoute
  '/admin/smoke': typeof AdminSmokeRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/api/estimate': typeof ApiEstimateRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/cli/authorize': typeof CliAuthorizeRoute
  '/creator/dashboard': typeof CreatorDashboardRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/r/$token': typeof RTokenRoute
  '/cli/': typeof CliIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/admin/run-smoke-step14': typeof ApiAdminRunSmokeStep14Route
  '/api/admin/upload-site-image': typeof ApiAdminUploadSiteImageRoute
  '/api/public/check-api-balances': typeof ApiPublicCheckApiBalancesRoute
  '/api/public/free-monthly-grant': typeof ApiPublicFreeMonthlyGrantRoute
  '/api/public/generate': typeof ApiPublicGenerateRoute
  '/api/public/lifecycle-emails': typeof ApiPublicLifecycleEmailsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/site-images': typeof ApiPublicSiteImagesRoute
  '/api/public/watermark-image': typeof ApiPublicWatermarkImageRoute
  '/api/public/watermark-video': typeof ApiPublicWatermarkVideoRoute
  '/api/ugc-line/images': typeof ApiUgcLineImagesRoute
  '/api/ugc-line/scripts': typeof ApiUgcLineScriptsRoute
  '/api/ugc-line/variations': typeof ApiUgcLineVariationsRoute
  '/api/video-agent/enhance': typeof ApiVideoAgentEnhanceRoute
  '/api/video-agent/finalize': typeof ApiVideoAgentFinalizeRoute
  '/api/video-agent/generate': typeof ApiVideoAgentGenerateRoute
  '/api/video-agent/messages': typeof ApiVideoAgentMessagesRoute
  '/api/video-agent/submit': typeof ApiVideoAgentSubmitRoute
  '/api/public/jobs/tick': typeof ApiPublicJobsTickRoute
  '/api/public/payments/sweep-stuck': typeof ApiPublicPaymentsSweepStuckRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/workers/health': typeof ApiPublicWorkersHealthRoute
  '/api/public/workers/register': typeof ApiPublicWorkersRegisterRoute
  '/api/video-agent/status/$videoId': typeof ApiVideoAgentStatusVideoIdRoute
  '/api/public/cli/device/poll': typeof ApiPublicCliDevicePollRoute
  '/api/public/cli/device/start': typeof ApiPublicCliDeviceStartRoute
  '/api/public/workers/files/$name': typeof ApiPublicWorkersFilesNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/agent'
    | '/auth'
    | '/avatar'
    | '/billing'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/colors-show'
    | '/comfy'
    | '/connect'
    | '/contact'
    | '/content-machine'
    | '/dashboard'
    | '/edit'
    | '/editor'
    | '/gallery'
    | '/gifts'
    | '/growth'
    | '/heygen-templates'
    | '/home'
    | '/kids'
    | '/lipsync'
    | '/live-studio'
    | '/marketplace'
    | '/motion'
    | '/music-video'
    | '/nexusarb'
    | '/orchestrate'
    | '/partners'
    | '/photo-edit'
    | '/privacy'
    | '/reset-password'
    | '/reshoot'
    | '/roadmap'
    | '/scene-builder'
    | '/settings'
    | '/sitemap.xml'
    | '/speech'
    | '/spin'
    | '/split-reality'
    | '/storyboard'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/tiktok'
    | '/tutorial'
    | '/ugc'
    | '/ugc-line'
    | '/video-editor'
    | '/workflows'
    | '/beat-reel'
    | '/admin/assets'
    | '/admin/comfy'
    | '/admin/costs'
    | '/admin/orchestration'
    | '/admin/site-images'
    | '/admin/smoke'
    | '/admin/templates'
    | '/admin/workflows'
    | '/api/estimate'
    | '/api/health'
    | '/api/mcp'
    | '/cli/authorize'
    | '/creator/dashboard'
    | '/guides/$slug'
    | '/legal/$slug'
    | '/r/$token'
    | '/cli/'
    | '/guides/'
    | '/api/admin/run-smoke-step14'
    | '/api/admin/upload-site-image'
    | '/api/public/check-api-balances'
    | '/api/public/free-monthly-grant'
    | '/api/public/generate'
    | '/api/public/lifecycle-emails'
    | '/api/public/paystack-webhook'
    | '/api/public/site-images'
    | '/api/public/watermark-image'
    | '/api/public/watermark-video'
    | '/api/ugc-line/images'
    | '/api/ugc-line/scripts'
    | '/api/ugc-line/variations'
    | '/api/video-agent/enhance'
    | '/api/video-agent/finalize'
    | '/api/video-agent/generate'
    | '/api/video-agent/messages'
    | '/api/video-agent/submit'
    | '/api/public/jobs/tick'
    | '/api/public/payments/sweep-stuck'
    | '/api/public/tiktok/callback'
    | '/api/public/workers/health'
    | '/api/public/workers/register'
    | '/api/video-agent/status/$videoId'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
    | '/api/public/workers/files/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliate'
    | '/agent'
    | '/auth'
    | '/avatar'
    | '/billing'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/colors-show'
    | '/comfy'
    | '/connect'
    | '/contact'
    | '/content-machine'
    | '/dashboard'
    | '/edit'
    | '/editor'
    | '/gallery'
    | '/gifts'
    | '/growth'
    | '/heygen-templates'
    | '/home'
    | '/kids'
    | '/lipsync'
    | '/live-studio'
    | '/marketplace'
    | '/motion'
    | '/music-video'
    | '/nexusarb'
    | '/orchestrate'
    | '/partners'
    | '/photo-edit'
    | '/privacy'
    | '/reset-password'
    | '/reshoot'
    | '/roadmap'
    | '/scene-builder'
    | '/settings'
    | '/sitemap.xml'
    | '/speech'
    | '/spin'
    | '/split-reality'
    | '/storyboard'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/tiktok'
    | '/tutorial'
    | '/ugc'
    | '/ugc-line'
    | '/video-editor'
    | '/workflows'
    | '/beat-reel'
    | '/admin/assets'
    | '/admin/comfy'
    | '/admin/costs'
    | '/admin/orchestration'
    | '/admin/site-images'
    | '/admin/smoke'
    | '/admin/templates'
    | '/admin/workflows'
    | '/api/estimate'
    | '/api/health'
    | '/api/mcp'
    | '/cli/authorize'
    | '/creator/dashboard'
    | '/guides/$slug'
    | '/legal/$slug'
    | '/r/$token'
    | '/cli'
    | '/guides'
    | '/api/admin/run-smoke-step14'
    | '/api/admin/upload-site-image'
    | '/api/public/check-api-balances'
    | '/api/public/free-monthly-grant'
    | '/api/public/generate'
    | '/api/public/lifecycle-emails'
    | '/api/public/paystack-webhook'
    | '/api/public/site-images'
    | '/api/public/watermark-image'
    | '/api/public/watermark-video'
    | '/api/ugc-line/images'
    | '/api/ugc-line/scripts'
    | '/api/ugc-line/variations'
    | '/api/video-agent/enhance'
    | '/api/video-agent/finalize'
    | '/api/video-agent/generate'
    | '/api/video-agent/messages'
    | '/api/video-agent/submit'
    | '/api/public/jobs/tick'
    | '/api/public/payments/sweep-stuck'
    | '/api/public/tiktok/callback'
    | '/api/public/workers/health'
    | '/api/public/workers/register'
    | '/api/video-agent/status/$videoId'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
    | '/api/public/workers/files/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate'
    | '/agent'
    | '/auth'
    | '/avatar'
    | '/billing'
    | '/canvas'
    | '/clips'
    | '/colors'
    | '/colors-show'
    | '/comfy'
    | '/connect'
    | '/contact'
    | '/content-machine'
    | '/dashboard'
    | '/edit'
    | '/editor'
    | '/gallery'
    | '/gifts'
    | '/growth'
    | '/heygen-templates'
    | '/home'
    | '/kids'
    | '/lipsync'
    | '/live-studio'
    | '/marketplace'
    | '/motion'
    | '/music-video'
    | '/nexusarb'
    | '/orchestrate'
    | '/partners'
    | '/photo-edit'
    | '/privacy'
    | '/reset-password'
    | '/reshoot'
    | '/roadmap'
    | '/scene-builder'
    | '/settings'
    | '/sitemap.xml'
    | '/speech'
    | '/spin'
    | '/split-reality'
    | '/storyboard'
    | '/studio'
    | '/templates'
    | '/terms'
    | '/tiktok'
    | '/tutorial'
    | '/ugc'
    | '/ugc-line'
    | '/video-editor'
    | '/workflows'
    | '/beat-reel'
    | '/admin/assets'
    | '/admin/comfy'
    | '/admin/costs'
    | '/admin/orchestration'
    | '/admin/site-images'
    | '/admin/smoke'
    | '/admin/templates'
    | '/admin/workflows'
    | '/api/estimate'
    | '/api/health'
    | '/api/mcp'
    | '/cli/authorize'
    | '/creator/dashboard'
    | '/guides/$slug'
    | '/legal/$slug'
    | '/r/$token'
    | '/cli/'
    | '/guides/'
    | '/api/admin/run-smoke-step14'
    | '/api/admin/upload-site-image'
    | '/api/public/check-api-balances'
    | '/api/public/free-monthly-grant'
    | '/api/public/generate'
    | '/api/public/lifecycle-emails'
    | '/api/public/paystack-webhook'
    | '/api/public/site-images'
    | '/api/public/watermark-image'
    | '/api/public/watermark-video'
    | '/api/ugc-line/images'
    | '/api/ugc-line/scripts'
    | '/api/ugc-line/variations'
    | '/api/video-agent/enhance'
    | '/api/video-agent/finalize'
    | '/api/video-agent/generate'
    | '/api/video-agent/messages'
    | '/api/video-agent/submit'
    | '/api/public/jobs/tick'
    | '/api/public/payments/sweep-stuck'
    | '/api/public/tiktok/callback'
    | '/api/public/workers/health'
    | '/api/public/workers/register'
    | '/api/video-agent/status/$videoId'
    | '/api/public/cli/device/poll'
    | '/api/public/cli/device/start'
    | '/api/public/workers/files/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  AvatarRoute: typeof AvatarRoute
  BillingRoute: typeof BillingRoute
  CanvasRoute: typeof CanvasRoute
  ClipsRoute: typeof ClipsRoute
  ColorsRoute: typeof ColorsRoute
  ColorsShowRoute: typeof ColorsShowRoute
  ComfyRoute: typeof ComfyRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  ContentMachineRoute: typeof ContentMachineRoute
  DashboardRoute: typeof DashboardRoute
  EditRoute: typeof EditRoute
  EditorRoute: typeof EditorRoute
  GalleryRoute: typeof GalleryRoute
  GiftsRoute: typeof GiftsRoute
  GrowthRoute: typeof GrowthRoute
  HeygenTemplatesRoute: typeof HeygenTemplatesRoute
  HomeRoute: typeof HomeRoute
  KidsRoute: typeof KidsRoute
  LipsyncRoute: typeof LipsyncRoute
  LiveStudioRoute: typeof LiveStudioRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MotionRoute: typeof MotionRoute
  MusicVideoRoute: typeof MusicVideoRoute
  NexusarbRoute: typeof NexusarbRoute
  OrchestrateRoute: typeof OrchestrateRoute
  PartnersRoute: typeof PartnersRoute
  PhotoEditRoute: typeof PhotoEditRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReshootRoute: typeof ReshootRoute
  RoadmapRoute: typeof RoadmapRoute
  SceneBuilderRoute: typeof SceneBuilderRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeechRoute: typeof SpeechRoute
  SpinRoute: typeof SpinRoute
  SplitRealityRoute: typeof SplitRealityRoute
  StoryboardRoute: typeof StoryboardRoute
  StudioRoute: typeof StudioRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  TiktokRoute: typeof TiktokRoute
  TutorialRoute: typeof TutorialRoute
  UgcRoute: typeof UgcRoute
  UgcLineRoute: typeof UgcLineRoute
  VideoEditorRoute: typeof VideoEditorRoute
  WorkflowsRoute: typeof WorkflowsRoute
  BeatReelLazyRoute: typeof BeatReelLazyRoute
  ApiEstimateRoute: typeof ApiEstimateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  CliAuthorizeRoute: typeof CliAuthorizeRoute
  CreatorDashboardRoute: typeof CreatorDashboardRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  RTokenRoute: typeof RTokenRoute
  CliIndexRoute: typeof CliIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ApiAdminRunSmokeStep14Route: typeof ApiAdminRunSmokeStep14Route
  ApiAdminUploadSiteImageRoute: typeof ApiAdminUploadSiteImageRoute
  ApiPublicCheckApiBalancesRoute: typeof ApiPublicCheckApiBalancesRoute
  ApiPublicFreeMonthlyGrantRoute: typeof ApiPublicFreeMonthlyGrantRoute
  ApiPublicGenerateRoute: typeof ApiPublicGenerateRoute
  ApiPublicLifecycleEmailsRoute: typeof ApiPublicLifecycleEmailsRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicSiteImagesRoute: typeof ApiPublicSiteImagesRoute
  ApiPublicWatermarkImageRoute: typeof ApiPublicWatermarkImageRoute
  ApiPublicWatermarkVideoRoute: typeof ApiPublicWatermarkVideoRoute
  ApiUgcLineImagesRoute: typeof ApiUgcLineImagesRoute
  ApiUgcLineScriptsRoute: typeof ApiUgcLineScriptsRoute
  ApiUgcLineVariationsRoute: typeof ApiUgcLineVariationsRoute
  ApiVideoAgentEnhanceRoute: typeof ApiVideoAgentEnhanceRoute
  ApiVideoAgentFinalizeRoute: typeof ApiVideoAgentFinalizeRoute
  ApiVideoAgentGenerateRoute: typeof ApiVideoAgentGenerateRoute
  ApiVideoAgentMessagesRoute: typeof ApiVideoAgentMessagesRoute
  ApiVideoAgentSubmitRoute: typeof ApiVideoAgentSubmitRoute
  ApiPublicJobsTickRoute: typeof ApiPublicJobsTickRoute
  ApiPublicPaymentsSweepStuckRoute: typeof ApiPublicPaymentsSweepStuckRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
  ApiPublicWorkersHealthRoute: typeof ApiPublicWorkersHealthRoute
  ApiPublicWorkersRegisterRoute: typeof ApiPublicWorkersRegisterRoute
  ApiVideoAgentStatusVideoIdRoute: typeof ApiVideoAgentStatusVideoIdRoute
  ApiPublicCliDevicePollRoute: typeof ApiPublicCliDevicePollRoute
  ApiPublicCliDeviceStartRoute: typeof ApiPublicCliDeviceStartRoute
  ApiPublicWorkersFilesNameRoute: typeof ApiPublicWorkersFilesNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beat-reel': {
      id: '/beat-reel'
      path: '/beat-reel'
      fullPath: '/beat-reel'
      preLoaderRoute: typeof BeatReelLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors-show': {
      id: '/colors-show'
      path: '/colors-show'
      fullPath: '/colors-show'
      preLoaderRoute: typeof ColorsShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comfy': {
      id: '/comfy'
      path: '/comfy'
      fullPath: '/comfy'
      preLoaderRoute: typeof ComfyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-machine': {
      id: '/content-machine'
      path: '/content-machine'
      fullPath: '/content-machine'
      preLoaderRoute: typeof ContentMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heygen-templates': {
      id: '/heygen-templates'
      path: '/heygen-templates'
      fullPath: '/heygen-templates'
      preLoaderRoute: typeof HeygenTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lipsync': {
      id: '/lipsync'
      path: '/lipsync'
      fullPath: '/lipsync'
      preLoaderRoute: typeof LipsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-studio': {
      id: '/live-studio'
      path: '/live-studio'
      fullPath: '/live-studio'
      preLoaderRoute: typeof LiveStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion': {
      id: '/motion'
      path: '/motion'
      fullPath: '/motion'
      preLoaderRoute: typeof MotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-video': {
      id: '/music-video'
      path: '/music-video'
      fullPath: '/music-video'
      preLoaderRoute: typeof MusicVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexusarb': {
      id: '/nexusarb'
      path: '/nexusarb'
      fullPath: '/nexusarb'
      preLoaderRoute: typeof NexusarbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orchestrate': {
      id: '/orchestrate'
      path: '/orchestrate'
      fullPath: '/orchestrate'
      preLoaderRoute: typeof OrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-edit': {
      id: '/photo-edit'
      path: '/photo-edit'
      fullPath: '/photo-edit'
      preLoaderRoute: typeof PhotoEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reshoot': {
      id: '/reshoot'
      path: '/reshoot'
      fullPath: '/reshoot'
      preLoaderRoute: typeof ReshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-builder': {
      id: '/scene-builder'
      path: '/scene-builder'
      fullPath: '/scene-builder'
      preLoaderRoute: typeof SceneBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech': {
      id: '/speech'
      path: '/speech'
      fullPath: '/speech'
      preLoaderRoute: typeof SpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-reality': {
      id: '/split-reality'
      path: '/split-reality'
      fullPath: '/split-reality'
      preLoaderRoute: typeof SplitRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storyboard': {
      id: '/storyboard'
      path: '/storyboard'
      fullPath: '/storyboard'
      preLoaderRoute: typeof StoryboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc': {
      id: '/ugc'
      path: '/ugc'
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc-line': {
      id: '/ugc-line'
      path: '/ugc-line'
      fullPath: '/ugc-line'
      preLoaderRoute: typeof UgcLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-editor': {
      id: '/video-editor'
      path: '/video-editor'
      fullPath: '/video-editor'
      preLoaderRoute: typeof VideoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comfy': {
      id: '/admin/comfy'
      path: '/comfy'
      fullPath: '/admin/comfy'
      preLoaderRoute: typeof AdminComfyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/costs': {
      id: '/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orchestration': {
      id: '/admin/orchestration'
      path: '/orchestration'
      fullPath: '/admin/orchestration'
      preLoaderRoute: typeof AdminOrchestrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-images': {
      id: '/admin/site-images'
      path: '/site-images'
      fullPath: '/admin/site-images'
      preLoaderRoute: typeof AdminSiteImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/smoke': {
      id: '/admin/smoke'
      path: '/smoke'
      fullPath: '/admin/smoke'
      preLoaderRoute: typeof AdminSmokeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/estimate': {
      id: '/api/estimate'
      path: '/api/estimate'
      fullPath: '/api/estimate'
      preLoaderRoute: typeof ApiEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/': {
      id: '/cli/'
      path: '/cli'
      fullPath: '/cli/'
      preLoaderRoute: typeof CliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/authorize': {
      id: '/cli/authorize'
      path: '/cli/authorize'
      fullPath: '/cli/authorize'
      preLoaderRoute: typeof CliAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/dashboard': {
      id: '/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof CreatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/run-smoke-step14': {
      id: '/api/admin/run-smoke-step14'
      path: '/api/admin/run-smoke-step14'
      fullPath: '/api/admin/run-smoke-step14'
      preLoaderRoute: typeof ApiAdminRunSmokeStep14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-site-image': {
      id: '/api/admin/upload-site-image'
      path: '/api/admin/upload-site-image'
      fullPath: '/api/admin/upload-site-image'
      preLoaderRoute: typeof ApiAdminUploadSiteImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-api-balances': {
      id: '/api/public/check-api-balances'
      path: '/api/public/check-api-balances'
      fullPath: '/api/public/check-api-balances'
      preLoaderRoute: typeof ApiPublicCheckApiBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/free-monthly-grant': {
      id: '/api/public/free-monthly-grant'
      path: '/api/public/free-monthly-grant'
      fullPath: '/api/public/free-monthly-grant'
      preLoaderRoute: typeof ApiPublicFreeMonthlyGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate': {
      id: '/api/public/generate'
      path: '/api/public/generate'
      fullPath: '/api/public/generate'
      preLoaderRoute: typeof ApiPublicGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lifecycle-emails': {
      id: '/api/public/lifecycle-emails'
      path: '/api/public/lifecycle-emails'
      fullPath: '/api/public/lifecycle-emails'
      preLoaderRoute: typeof ApiPublicLifecycleEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-images': {
      id: '/api/public/site-images'
      path: '/api/public/site-images'
      fullPath: '/api/public/site-images'
      preLoaderRoute: typeof ApiPublicSiteImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/watermark-image': {
      id: '/api/public/watermark-image'
      path: '/api/public/watermark-image'
      fullPath: '/api/public/watermark-image'
      preLoaderRoute: typeof ApiPublicWatermarkImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/watermark-video': {
      id: '/api/public/watermark-video'
      path: '/api/public/watermark-video'
      fullPath: '/api/public/watermark-video'
      preLoaderRoute: typeof ApiPublicWatermarkVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ugc-line/images': {
      id: '/api/ugc-line/images'
      path: '/api/ugc-line/images'
      fullPath: '/api/ugc-line/images'
      preLoaderRoute: typeof ApiUgcLineImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ugc-line/scripts': {
      id: '/api/ugc-line/scripts'
      path: '/api/ugc-line/scripts'
      fullPath: '/api/ugc-line/scripts'
      preLoaderRoute: typeof ApiUgcLineScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ugc-line/variations': {
      id: '/api/ugc-line/variations'
      path: '/api/ugc-line/variations'
      fullPath: '/api/ugc-line/variations'
      preLoaderRoute: typeof ApiUgcLineVariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-agent/enhance': {
      id: '/api/video-agent/enhance'
      path: '/api/video-agent/enhance'
      fullPath: '/api/video-agent/enhance'
      preLoaderRoute: typeof ApiVideoAgentEnhanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-agent/finalize': {
      id: '/api/video-agent/finalize'
      path: '/api/video-agent/finalize'
      fullPath: '/api/video-agent/finalize'
      preLoaderRoute: typeof ApiVideoAgentFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-agent/generate': {
      id: '/api/video-agent/generate'
      path: '/api/video-agent/generate'
      fullPath: '/api/video-agent/generate'
      preLoaderRoute: typeof ApiVideoAgentGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-agent/messages': {
      id: '/api/video-agent/messages'
      path: '/api/video-agent/messages'
      fullPath: '/api/video-agent/messages'
      preLoaderRoute: typeof ApiVideoAgentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-agent/submit': {
      id: '/api/video-agent/submit'
      path: '/api/video-agent/submit'
      fullPath: '/api/video-agent/submit'
      preLoaderRoute: typeof ApiVideoAgentSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/tick': {
      id: '/api/public/jobs/tick'
      path: '/api/public/jobs/tick'
      fullPath: '/api/public/jobs/tick'
      preLoaderRoute: typeof ApiPublicJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/sweep-stuck': {
      id: '/api/public/payments/sweep-stuck'
      path: '/api/public/payments/sweep-stuck'
      fullPath: '/api/public/payments/sweep-stuck'
      preLoaderRoute: typeof ApiPublicPaymentsSweepStuckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/health': {
      id: '/api/public/workers/health'
      path: '/api/public/workers/health'
      fullPath: '/api/public/workers/health'
      preLoaderRoute: typeof ApiPublicWorkersHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/register': {
      id: '/api/public/workers/register'
      path: '/api/public/workers/register'
      fullPath: '/api/public/workers/register'
      preLoaderRoute: typeof ApiPublicWorkersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-agent/status/$videoId': {
      id: '/api/video-agent/status/$videoId'
      path: '/api/video-agent/status/$videoId'
      fullPath: '/api/video-agent/status/$videoId'
      preLoaderRoute: typeof ApiVideoAgentStatusVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/device/poll': {
      id: '/api/public/cli/device/poll'
      path: '/api/public/cli/device/poll'
      fullPath: '/api/public/cli/device/poll'
      preLoaderRoute: typeof ApiPublicCliDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cli/device/start': {
      id: '/api/public/cli/device/start'
      path: '/api/public/cli/device/start'
      fullPath: '/api/public/cli/device/start'
      preLoaderRoute: typeof ApiPublicCliDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workers/files/$name': {
      id: '/api/public/workers/files/$name'
      path: '/api/public/workers/files/$name'
      fullPath: '/api/public/workers/files/$name'
      preLoaderRoute: typeof ApiPublicWorkersFilesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminComfyRoute: typeof AdminComfyRoute
  AdminCostsRoute: typeof AdminCostsRoute
  AdminOrchestrationRoute: typeof AdminOrchestrationRoute
  AdminSiteImagesRoute: typeof AdminSiteImagesRoute
  AdminSmokeRoute: typeof AdminSmokeRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssetsRoute: AdminAssetsRoute,
  AdminComfyRoute: AdminComfyRoute,
  AdminCostsRoute: AdminCostsRoute,
  AdminOrchestrationRoute: AdminOrchestrationRoute,
  AdminSiteImagesRoute: AdminSiteImagesRoute,
  AdminSmokeRoute: AdminSmokeRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  AvatarRoute: AvatarRoute,
  BillingRoute: BillingRoute,
  CanvasRoute: CanvasRoute,
  ClipsRoute: ClipsRoute,
  ColorsRoute: ColorsRoute,
  ColorsShowRoute: ColorsShowRoute,
  ComfyRoute: ComfyRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  ContentMachineRoute: ContentMachineRoute,
  DashboardRoute: DashboardRoute,
  EditRoute: EditRoute,
  EditorRoute: EditorRoute,
  GalleryRoute: GalleryRoute,
  GiftsRoute: GiftsRoute,
  GrowthRoute: GrowthRoute,
  HeygenTemplatesRoute: HeygenTemplatesRoute,
  HomeRoute: HomeRoute,
  KidsRoute: KidsRoute,
  LipsyncRoute: LipsyncRoute,
  LiveStudioRoute: LiveStudioRoute,
  MarketplaceRoute: MarketplaceRoute,
  MotionRoute: MotionRoute,
  MusicVideoRoute: MusicVideoRoute,
  NexusarbRoute: NexusarbRoute,
  OrchestrateRoute: OrchestrateRoute,
  PartnersRoute: PartnersRoute,
  PhotoEditRoute: PhotoEditRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReshootRoute: ReshootRoute,
  RoadmapRoute: RoadmapRoute,
  SceneBuilderRoute: SceneBuilderRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeechRoute: SpeechRoute,
  SpinRoute: SpinRoute,
  SplitRealityRoute: SplitRealityRoute,
  StoryboardRoute: StoryboardRoute,
  StudioRoute: StudioRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  TiktokRoute: TiktokRoute,
  TutorialRoute: TutorialRoute,
  UgcRoute: UgcRoute,
  UgcLineRoute: UgcLineRoute,
  VideoEditorRoute: VideoEditorRoute,
  WorkflowsRoute: WorkflowsRoute,
  BeatReelLazyRoute: BeatReelLazyRoute,
  ApiEstimateRoute: ApiEstimateRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  CliAuthorizeRoute: CliAuthorizeRoute,
  CreatorDashboardRoute: CreatorDashboardRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  RTokenRoute: RTokenRoute,
  CliIndexRoute: CliIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ApiAdminRunSmokeStep14Route: ApiAdminRunSmokeStep14Route,
  ApiAdminUploadSiteImageRoute: ApiAdminUploadSiteImageRoute,
  ApiPublicCheckApiBalancesRoute: ApiPublicCheckApiBalancesRoute,
  ApiPublicFreeMonthlyGrantRoute: ApiPublicFreeMonthlyGrantRoute,
  ApiPublicGenerateRoute: ApiPublicGenerateRoute,
  ApiPublicLifecycleEmailsRoute: ApiPublicLifecycleEmailsRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicSiteImagesRoute: ApiPublicSiteImagesRoute,
  ApiPublicWatermarkImageRoute: ApiPublicWatermarkImageRoute,
  ApiPublicWatermarkVideoRoute: ApiPublicWatermarkVideoRoute,
  ApiUgcLineImagesRoute: ApiUgcLineImagesRoute,
  ApiUgcLineScriptsRoute: ApiUgcLineScriptsRoute,
  ApiUgcLineVariationsRoute: ApiUgcLineVariationsRoute,
  ApiVideoAgentEnhanceRoute: ApiVideoAgentEnhanceRoute,
  ApiVideoAgentFinalizeRoute: ApiVideoAgentFinalizeRoute,
  ApiVideoAgentGenerateRoute: ApiVideoAgentGenerateRoute,
  ApiVideoAgentMessagesRoute: ApiVideoAgentMessagesRoute,
  ApiVideoAgentSubmitRoute: ApiVideoAgentSubmitRoute,
  ApiPublicJobsTickRoute: ApiPublicJobsTickRoute,
  ApiPublicPaymentsSweepStuckRoute: ApiPublicPaymentsSweepStuckRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
  ApiPublicWorkersHealthRoute: ApiPublicWorkersHealthRoute,
  ApiPublicWorkersRegisterRoute: ApiPublicWorkersRegisterRoute,
  ApiVideoAgentStatusVideoIdRoute: ApiVideoAgentStatusVideoIdRoute,
  ApiPublicCliDevicePollRoute: ApiPublicCliDevicePollRoute,
  ApiPublicCliDeviceStartRoute: ApiPublicCliDeviceStartRoute,
  ApiPublicWorkersFilesNameRoute: ApiPublicWorkersFilesNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
