-- user_photo_avatars: personal "talking photo" avatars a user saves for
-- repeated use. Each row holds the studio bucket path (not a signed URL —
-- the server re-signs at generation time). Videos are generated by combining
-- a stored photo with per-run TTS audio via the heygen/photo-video adapter.
create table if not exists public.user_photo_avatars (
  id            uuid        default gen_random_uuid() primary key,
  user_id       uuid        not null references auth.users (id) on delete cascade,
  name          text        not null check (char_length(name) between 1 and 100),
  storage_path  text        not null,
  created_at    timestamptz default now() not null
);

alter table public.user_photo_avatars enable row level security;

create policy "users manage own photo avatars"
  on public.user_photo_avatars
  for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists user_photo_avatars_user_idx
  on public.user_photo_avatars (user_id, created_at desc);
